const d = {
  status: 'Approved',
  shiftID: '992833',
  userId: '1',
  title: 'Servitør',
  salaryCode: '',
  team: 'Servitør',
  userName: 'Pontus lindroth W',
  accountantId: '',
  baseSalary: 500,
  start: 1721511000000,
  startDate: '20.07.24 21:30',
  end: 1721557800000,
  endDate: '21.07.24 10:30',
  shiftStatus: 4,
  employeeType: '',
  timezoneOffSet: '2',
  fasit: '7862.50',

  records: [],

  supplements: [
    {
      id: '1',
      title: 'Kveldstillegg',
      salaryCode: '2003',
      type: 'fromHourToHour',
      wageAdjustment: 'addToExistingAmount',
      pcsValue: 16.0,
      start: 1721509200,
      startPrint: '12.03.24 21:00',
      end: 1721520000,
      endPrint: '12.03.24 00:00',
      afterMinutes: '',
      duration: '',
      weekDays: '1, 2, 3, 4, 5, 6, 0',
      enforcePayment: 'nei',
      employeeTypes: '2001, 2001',
      activeOnHolyday: '',
      teams:
        'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod'
    },
    {
      id: '2',
      title: 'Nattillegg',
      salaryCode: '2003',
      type: 'fromHourToHour',
      wageAdjustment: 'addToExistingAmount',
      pcsValue: 55.0,
      start: 1721433600,
      startPrint: '12.03.24 00:00',
      end: 1721538000,
      endPrint: '12.03.24 05:00',
      afterMinutes: '',
      duration: '',
      weekDays: '1, 2, 3, 4, 5, 6, 0',
      enforcePayment: 'nei',
      employeeTypes: '2001, 2001',
      activeOnHolyday: '',
      teams:
        'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod'
    },
    {
      id: '5',
      title: 'Overtid 40%',
      salaryCode: '6001',
      type: 'afterXHours',
      wageAdjustment: '%',
      pcsValue: 40.0,
      start: 1721433600,
      startPrint: '11.07.24 00:00',
      end: 1721520000,
      endPrint: '11.07.34 00:00',
      afterMinutes: '540',
      duration: '59940',
      weekDays: '1, 2, 3, 4, 5, 6, 0',
      enforcePayment: 'nei',
      employeeTypes: '2001, 2001',
      activeOnHolyday: '',
      teams:
        'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Restaurant sjef, Kjøkken hjelp, Kjøkken Sjef, Kokk, Commis, Vert, Runner, 1.linje, Hagesjef, Burger sjappa, Bartender kjeller, Bartender terrassebar, Vakt kjeller, Bartender Minibar, Backbar kjeller, Kontor, Jr bartender festivalbar, Jr bartender pølsebod, Mat pølsebod'
    },
    {
      id: '8',
      title: 'Søndag',
      salaryCode: '3333',
      type: 'fromHourToHour',
      wageAdjustment: 'addToExistingAmount',
      pcsValue: 55.0,
      start: 1721455200,
      startPrint: '01.01.24 06:00',
      end: 1721520000,
      endPrint: '01.01.24 00:00',
      afterMinutes: '0',
      duration: '0',
      weekDays: '0',
      enforcePayment: 'nei',
      employeeTypes: '2001, 2001',
      activeOnHolyday: '',
      teams:
        'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Restaurant sjef, Kjøkken hjelp, Kjøkken Sjef, Kokk, Commis, Vert, Runner, 1.linje, Hagesjef, Burger sjappa, Bartender kjeller, Bartender terrassebar, Vakt kjeller, Bartender Minibar, Backbar kjeller, Kontor, Jr bartender festivalbar, Jr bartender pølsebod, Mat pølsebod'
    }
  ]
}

const array = [
  {
    status: 'Approved',
    shiftID: '992833',
    userId: '1',
    title: 'Servitør',
    salaryCode: '',
    team: 'Servitør',
    userName: 'Pontus lindroth W',
    accountantId: '',
    baseSalary: 500,
    start: 1721511000000,
    startDate: '20.07.24 21:30',
    end: 1721557800000,
    endDate: '21.07.24 10:30',
    shiftStatus: 4,
    employeeType: '',
    timezoneOffSet: '2',
    fasit: '7862.50',

    records: [],

    supplements: [
      {
        id: '1',
        title: 'Kveldstillegg',
        salaryCode: '2003',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 16.0,
        start: 1721509200,
        startPrint: '12.03.24 21:00',
        end: 1721520000,
        endPrint: '12.03.24 00:00',
        afterMinutes: '',
        duration: '',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        enforcePayment: 'nei',
        employeeTypes: '2001, 2001',
        activeOnHolyday: '',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod'
      },
      {
        id: '2',
        title: 'Nattillegg',
        salaryCode: '2003',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 55.0,
        start: 1721433600,
        startPrint: '12.03.24 00:00',
        end: 1721538000,
        endPrint: '12.03.24 05:00',
        afterMinutes: '',
        duration: '',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        enforcePayment: 'nei',
        employeeTypes: '2001, 2001',
        activeOnHolyday: '',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod'
      },
      {
        id: '5',
        title: 'Overtid 40%',
        salaryCode: '6001',
        type: 'afterXHours',
        wageAdjustment: '%',
        pcsValue: 40.0,
        start: 1721433600,
        startPrint: '11.07.24 00:00',
        end: 1721520000,
        endPrint: '11.07.34 00:00',
        afterMinutes: '540',
        duration: '59940',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        enforcePayment: 'nei',
        employeeTypes: '2001, 2001',
        activeOnHolyday: '',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Restaurant sjef, Kjøkken hjelp, Kjøkken Sjef, Kokk, Commis, Vert, Runner, 1.linje, Hagesjef, Burger sjappa, Bartender kjeller, Bartender terrassebar, Vakt kjeller, Bartender Minibar, Backbar kjeller, Kontor, Jr bartender festivalbar, Jr bartender pølsebod, Mat pølsebod'
      },
      {
        id: '8',
        title: 'Søndag',
        salaryCode: '3333',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 55.0,
        start: 1721455200,
        startPrint: '01.01.24 06:00',
        end: 1721520000,
        endPrint: '01.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '0',
        enforcePayment: 'nei',
        employeeTypes: '2001, 2001',
        activeOnHolyday: '',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Restaurant sjef, Kjøkken hjelp, Kjøkken Sjef, Kokk, Commis, Vert, Runner, 1.linje, Hagesjef, Burger sjappa, Bartender kjeller, Bartender terrassebar, Vakt kjeller, Bartender Minibar, Backbar kjeller, Kontor, Jr bartender festivalbar, Jr bartender pølsebod, Mat pølsebod'
      }
    ]
  },
  {
    status: 'Approved',
    shiftID: '220392',
    userId: '1',
    title: 'Servitør',
    salaryCode: '2001',
    team: 'Servitør',
    userName: 'Pontus lindroth W',
    accountantId: '422',
    baseSalary: 500,
    start: 1721480400000,
    startDate: '20.07.24 13:00',
    end: 1721530800000,
    endDate: '21.07.24 03:00',
    shiftStatus: 4,
    employeeType: 'Timelønn sesongmedarbeider',
    timezoneOffSet: '2',
    fasit: '7863.00',

    records: [
      {
        title: '1337',
        type: 'workTime',
        start: 1721480400,
        startPrint: '20.07.2024 13:00',
        end: 1721530800,
        endPrint: '21.07.2024 03:00',
        id: 2001,
        value: 50400.0,
        salaryCode: 2001,
        amount: 0.0
      },
      {
        title: 'Pause etter 6h',
        type: 'supplement',
        start: 1721502000,
        startPrint: '20.07.2024 19:00',
        end: 1721503800,
        endPrint: '20.07.2024 19:30',
        id: 9764,
        value: 0.5,
        salaryCode: 9764,
        amount: -250.0
      },
      {
        title: 'Måltidsfradrag ',
        type: 'supplement',
        start: 1721502000,
        startPrint: '20.07.2024 19:00',
        end: 1721502000,
        endPrint: '20.07.2024 19:00',
        id: 343,
        value: 1.0,
        salaryCode: 343,
        amount: -50.0
      }
    ],

    supplements: [
      {
        id: '1',
        title: 'Kveldstillegg',
        salaryCode: '2003',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 16.0,
        start: 1721509200,
        startPrint: '12.03.24 21:00',
        end: 1721520000,
        endPrint: '12.03.24 00:00',
        afterMinutes: '',
        duration: '',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '2001, 2001',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod'
      },
      {
        id: '2',
        title: 'Nattillegg',
        salaryCode: '2003',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 55.0,
        start: 1721433600,
        startPrint: '12.03.24 00:00',
        end: 1721538000,
        endPrint: '12.03.24 05:00',
        afterMinutes: '',
        duration: '',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '2001, 2001',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod'
      },
      {
        id: '5',
        title: 'Overtid 40%',
        salaryCode: '6001',
        type: 'afterXHours',
        wageAdjustment: '%',
        pcsValue: 40.0,
        start: 1721433600,
        startPrint: '11.07.24 00:00',
        end: 1721520000,
        endPrint: '11.07.34 00:00',
        afterMinutes: '540',
        duration: '59940',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '2001, 2001',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Restaurant sjef, Kjøkken hjelp, Kjøkken Sjef, Kokk, Commis, Vert, Runner, 1.linje, Hagesjef, Burger sjappa, Bartender kjeller, Bartender terrassebar, Vakt kjeller, Bartender Minibar, Backbar kjeller, Kontor, Jr bartender festivalbar, Jr bartender pølsebod, Mat pølsebod'
      },
      {
        id: '6',
        title: 'Pause etter 6h',
        salaryCode: '9764',
        type: 'fixed',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 0.0,
        start: 1721480400,
        startPrint: '',
        end: 1721530800,
        endPrint: '',
        afterMinutes: '360',
        duration: '30',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'null',
        employeeTypes: '2001, 2001',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Restaurant sjef, Kjøkken hjelp, Kjøkken Sjef, Kokk, Commis, Vert, Runner, 1.linje, Hagesjef, Burger sjappa, Bartender kjeller, Bartender terrassebar, Vakt kjeller, Bartender Minibar, Backbar kjeller, Kontor, Jr bartender festivalbar, Jr bartender pølsebod, Mat pølsebod'
      },
      {
        id: '6',
        title: 'Måltidsfradrag ',
        salaryCode: '343',
        type: 'afterXHours',
        wageAdjustment: 'fixed',
        pcsValue: -50.0,
        start: 1721480400,
        startPrint: '',
        end: 1721530800,
        endPrint: '',
        afterMinutes: '360',
        duration: '1',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'null',
        employeeTypes: '2001, 2001',
        teams:
          'Servitør, Hovmester, Vert Restaurant, Bartender Restaurant, Bartender kjeller, Vert, Runner, Kjøkken Sjef, Kokk, Commis, Restaurant sjef, Kontor, Bartender terrassebar, 1.linje, Vakt kjeller, Bartender Minibar, Backbar kjeller, Hagesjef, Jr bartender festivalbar, Jr bartender pølsebod, Jr bartender pølsebod, Mat pølsebod, Mat pølsebod, Kjøkken hjelp, Burger sjappa'
      }
    ]
  },
  {
    status: 'Approved',
    shiftID: '939504',
    userId: '1',
    title: 'Servitør',
    salaryCode: '1',
    team: 'Servitør',
    userName: 'Pontus S. Lindroth ',
    accountantId: '12',
    baseSalary: 250,
    start: 1721516400000,
    startDate: '20.07.24 23:00',
    end: 1721552400000,
    endDate: '21.07.24 09:00',
    shiftStatus: 4,
    employeeType: 'Hour salary',
    timezoneOffSet: '2',
    fasit: '2478.00',

    records: [
      {
        title: '1337',
        type: 'workTime',
        start: 1721516400,
        startPrint: '20.07.2024 23:00',
        end: 1721552400,
        endPrint: '21.07.2024 09:00',
        id: 1,
        value: 36000.0,
        salaryCode: 1,
        amount: 0.0
      },
      {
        title: 'Pause etter 6h',
        type: 'supplement',
        start: 1721538000,
        startPrint: '21.07.2024 05:00',
        end: 1721539800,
        endPrint: '21.07.2024 05:30',
        id: 6451,
        value: 0.5,
        salaryCode: 6451,
        amount: -125.0
      }
    ],

    supplements: [
      {
        id: '3',
        title: 'Søndag tillegg',
        salaryCode: '21',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 25.75,
        start: 1721455200,
        startPrint: '30.01.24 06:00',
        end: 1721520000,
        endPrint: '30.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '0',
        range: 'week',
        employeeTypes: '1, 1, 64',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner'
      },
      {
        id: '2',
        title: 'Lørdag tillegg',
        salaryCode: '20',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 25.75,
        start: 1721484000,
        startPrint: '31.01.24 14:00',
        end: 1721520000,
        endPrint: '31.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '6',
        range: 'week',
        employeeTypes: '1, 1, 64',
        teams:
          'First pioneers, Employee, Developer, Employee, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      },
      {
        id: '12',
        title: 'Pause etter 6h',
        salaryCode: '6451',
        type: 'fixed',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 0.0,
        start: 1721516400,
        startPrint: '',
        end: 1721552400,
        endPrint: '',
        afterMinutes: '360',
        duration: '30',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'null',
        employeeTypes: '1, 64',
        teams:
          'First pioneers, Employee, Developer, Employee, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      }
    ]
  },
  {
    status: 'Approved',
    shiftID: '820781',
    userId: '1',
    title: 'Servitør',
    salaryCode: '1',
    team: 'Servitør',
    userName: 'Pontus S. Lindroth ',
    accountantId: '12',
    baseSalary: 250,
    start: 1721415600000,
    startDate: '19.07.24 19:00',
    end: 1721430000000,
    endDate: '19.07.24 23:00',
    shiftStatus: 4,
    employeeType: 'Hour salary',
    timezoneOffSet: '2',
    fasit: '1000.00',

    records: [
      {
        title: '1337',
        type: 'workTime',
        start: 1721415600,
        startPrint: '19.07.2024 19:00',
        end: 1721430000,
        endPrint: '19.07.2024 23:00',
        id: 1,
        value: 14400.0,
        salaryCode: 1,
        amount: 0.0
      }
    ],

    supplements: [
      {
        id: '4',
        title: 'Overtid 40%',
        salaryCode: '17',
        type: 'afterXHours',
        wageAdjustment: '%',
        pcsValue: 40.0,
        start: 1721347200,
        startPrint: '31.01.24 00:00',
        end: 1721347200,
        endPrint: '31.01.24 00:00',
        afterMinutes: '540',
        duration: '59940',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      },
      {
        id: '3',
        title: 'Søndag tillegg',
        salaryCode: '21',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 25.75,
        start: 1721368800,
        startPrint: '30.01.24 06:00',
        end: 1721347200,
        endPrint: '30.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '0',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner'
      },
      {
        id: '2',
        title: 'Lørdag tillegg',
        salaryCode: '20',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 25.75,
        start: 1721397600,
        startPrint: '31.01.24 14:00',
        end: 1721347200,
        endPrint: '31.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '6',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner'
      },
      {
        id: '12',
        title: 'Natttillegg',
        salaryCode: '9465',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 47.41,
        start: 1721347200,
        startPrint: '14.07.24 00:00',
        end: 1721361600,
        endPrint: '14.07.24 04:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Developer, Employee, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      },
      {
        id: '12',
        title: 'Pause etter 6h',
        salaryCode: '6451',
        type: 'fixed',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 0.0,
        start: 1721415600,
        startPrint: '',
        end: 1721430000,
        endPrint: '',
        afterMinutes: '360',
        duration: '30',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'null',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Developer, Employee, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      }
    ]
  },
  {
    status: 'Approved',
    shiftID: '65974',
    userId: '1',
    title: 'Servitør',
    salaryCode: '1',
    team: 'Servitør',
    userName: 'Pontus S. Lindroth ',
    accountantId: '12',
    baseSalary: 250,
    start: 1721502000000,
    startDate: '20.07.24 19:00',
    end: 1721516400000,
    endDate: '20.07.24 23:00',
    shiftStatus: 4,
    employeeType: 'Hour salary',
    timezoneOffSet: '2',
    fasit: '1103.00',

    records: [
      {
        title: '1337',
        type: 'workTime',
        start: 1721502000,
        startPrint: '20.07.2024 19:00',
        end: 1721516400,
        endPrint: '20.07.2024 23:00',
        id: 1,
        value: 14400.0,
        salaryCode: 1,
        amount: 0.0
      }
    ],

    supplements: [
      {
        id: '4',
        title: 'Overtid 40%',
        salaryCode: '17',
        type: 'afterXHours',
        wageAdjustment: '%',
        pcsValue: 40.0,
        start: 1721433600,
        startPrint: '31.01.24 00:00',
        end: 1721433600,
        endPrint: '31.01.24 00:00',
        afterMinutes: '540',
        duration: '59940',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      },
      {
        id: '3',
        title: 'Søndag tillegg',
        salaryCode: '21',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 25.75,
        start: 1721455200,
        startPrint: '30.01.24 06:00',
        end: 1721433600,
        endPrint: '30.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '0',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner'
      },
      {
        id: '2',
        title: 'Lørdag tillegg',
        salaryCode: '20',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 25.75,
        start: 1721484000,
        startPrint: '31.01.24 14:00',
        end: 1721433600,
        endPrint: '31.01.24 00:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '6',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Employee, Waiter, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Båt vakter, Developer, Servitør, Runner'
      },
      {
        id: '12',
        title: 'Natttillegg',
        salaryCode: '9465',
        type: 'fromHourToHour',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 47.41,
        start: 1721433600,
        startPrint: '14.07.24 00:00',
        end: 1721448000,
        endPrint: '14.07.24 04:00',
        afterMinutes: '0',
        duration: '0',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'week',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Developer, Employee, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      },
      {
        id: '12',
        title: 'Pause etter 6h',
        salaryCode: '6451',
        type: 'fixed',
        wageAdjustment: 'addToExistingAmount',
        pcsValue: 0.0,
        start: 1721502000,
        startPrint: '',
        end: 1721516400,
        endPrint: '',
        afterMinutes: '360',
        duration: '30',
        weekDays: '1, 2, 3, 4, 5, 6, 0',
        range: 'null',
        employeeTypes: '1, 1',
        teams:
          'First pioneers, Employee, Developer, Employee, Systuen, Brettspill gjengen, Gründerkafe, Parkering, Båt vakter, Servitør, Runner, Hovmester, Administrasjon, Settefiskanlegg, Lærling, Junior Frisør, Elektor, Rør, Kunde, Faggruppe 1, Faggruppe 2'
      }
    ]
  }
]
export const indata = JSON.stringify(d)
export const indataArray = array.map((i) => JSON.stringify({ ...i, key: i.shiftID }))
